function ShellHardcodedAnimals() {

    return {
        'Snail': {
            opening: 1.66,
            displacement: 0,
            shape: 1.2,
            translation: 2,
            coarsegraininess: 4,
            reach: 5,
            pattern: "circle",
            handedness: 1,
            translationGradient: 1,
        },
        'Turitella': {
            opening: 1.30,
            displacement: 0,
            shape: 1,
            translation: 8.2,
            coarsegraininess: 8,
            reach: 10,
            pattern: "circle",
            handedness: 1,
            translationGradient: 1,  
        },
        'Bivalve': {
            opening: 1000,
            displacement: 0,
            shape: 1.2,
            translation: 0.5,
            mutProb: 50,
            coarsegraininess: 2,
            reach: 1,
            pattern: "circle",
            handedness: 1,
            translationGradient: 1,
        },
        Ammonite: {
            opening: 2,
            displacement: 0,
            shape: 1,
            translation: 0,
            coarsegraininess: 8,
            reach: 3,
            pattern: "circle",
            handedness: 1,
            translationGradient: 1,
        },
        Nautilus: {
            opening: 3.4,
            displacement: 0,
            shape: 1.2,
            translation: 0,
            coarsegraininess: 8,
            reach: 3,
            pattern: "circle",
            handedness: 1,
            translationGradient: 1,
        },
        Brachiopod: {
            opening: 10000,
            displacement: 0,
            shape: 1,
            translation: 0,
            coarsegraininess: 2,
            reach: 3,
            pattern: "circle",
            handedness: 1,
            translationGradient: 1,
        },
        Cone: {
            opening: 1.66,
            displacement: 0,
            shape: 3,
            translation: 3.5,
            coarsegraininess: 2,
            reach: 3,
            pattern: "whelk",
            handedness: 1,
            translationGradient: 1,
        },
        Whelk: {
            opening: 1.7,
            displacement: 0,
            shape: 2,
            translation: 4,
            coarsegraininess: 2,
            reach: 6,
            pattern: "whelk",
            handedness: 1,
            translationGradient: 1,

        },
        Scallop: {
            opening: 10000,
            displacement: 0,
            shape: 1,
            translation: 0,
            coarsegraininess: 2,
            reach: 3,
            pattern: "scallop",
            handedness: 1,
            translationGradient: 1,
        },
        Eloise: {
            opening: 1.4,
            displacement: 0,
            shape: 1.7,
            translation: 3.5,
            coarsegraininess: 4,
            reach: 6,
            pattern: "eloise",
            handedness: 1,
            translationGradient: 1,
        },
        Gallaghers: {
            opening: 1.66,
            displacement: 0,
            shape: 1.8,
            translation: 5,
            coarsegraininess: 4,
            reach: 6,
            pattern: "gallaghers",
            handedness: -1,
            translationGradient: 1,
        },
        Rapa: {
            opening: 1.66,
            displacement: 0,
            shape: 2,
            translation: 2.2,
            coarsegraininess: 4,
            reach: 9,
            pattern: "rapa",
            handedness: 1,
            translationGradient: 1,
        }, 
        Lightning: {
            opening: 1.66,
            displacement: 0,
            shape: 3.5,
            translation: 4,
            coarsegraininess: 4,
            reach: 6,
            pattern: "lightning",
            handedness: -1,
            translationGradient: 0.9,
        }, 
        Sundial: {
            opening: 1.384,
            displacement: 0.261,
            shape: 0.618,
            translation: 1.055,
            coarsegraininess: 2,
            reach: 10,
            pattern: "sundial", // pattern 152
            handedness: 1,
            translationGradient: 1,
        },
        Fig: {
            opening: 2,
            displacement: 0,
            shape: 3,
            translation: 3.5,
            coarsegraininess: 2,
            reach: 8,
            pattern: "tun", 
            handedness: 1,
            translationGradient: 0.95,
        }, 
        Tun: {
            opening: 2,
            displacement: 0,
            shape: 2,
            translation: 2.8,
            coarsegraininess: 2,
            reach: 8,
            pattern: "tun",
            handedness: 1,
            translationGradient: 1,
        },
        RazorShell: {
            opening: 1000,
            displacement: 0,
            shape: 8,
            translation: 6,
            coarsegraininess: 2,
            reach: 1,
            pattern: "razor",
            handedness: 1,
            translationGradient: 1,
        },
        JapaneseWonder: {
            opening: 1.7,
            displacement: 0,
            shape: 1.3,
            translation: 4.2,
            coarsegraininess: 2,
            reach: 8,
            pattern: "wonder",
            handedness: 1,
            translationGradient: 1,
        }
    }
}

